Compile with /Zc:strictStrings to avoid future string literal abuse
Microsoft's SetThreadName function uses a char* parameter which is
anachronism from the C days which I didn't notice when adding this
function. Building with /Zc:strictStrings prohibits conversions from
string literals to char* so this change enables this switch.

mshtml.h contains some bad function declarations that have BSTR
parameters that with string literal default values, like this:

        virtual /* [id] */ HRESULT STDMETHODCALLTYPE setExpression(
            /* [in] */ __RPC__in BSTR propname,
            /* [in] */ __RPC__in BSTR expression,
            /* [in][defaultvalue] */ __RPC__in BSTR language = L"") = 0;

This triggers lots of these errors:

1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\mshtml.h(16561): error C2440: 'default argument' : cannot convert from 'const wchar_t [1]' to 'BSTR'
1>          Conversion from string literal loses const qualifier (see /Zc:strictStrings)

Luckily I determined that "#define _ATL_NO_HOSTING" stops mshtml.h
from being included (ShowIncludes and walking up the hierarchy) which
was enough to get release configurations to build with strictStrings.

Debug builds don't build with strictStrings because the operator new
overloads use a char* parameter!

I then confirmed that strictStrings caches the SetCurrentThreadName
abuse:

1>DirectoryMonitor.cpp(30): error C2664: 'void SetCurrentThreadName(char *)' : cannot convert argument 1 from 'const char [25]' to 'char *'
1>          Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>UIforETW.cpp(164): error C2664: 'void SetCurrentThreadName(char *)' : cannot convert argument 1 from 'const char [12]' to 'char *'
1>          Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>  WorkingSet.cpp
1>PowerStatus.cpp(257): error C2664: 'void SetCurrentThreadName(char *)' : cannot convert argument 1 from 'const char [21]' to 'char *'
1>          Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>KeyLoggerThread.cpp(195): error C2664: 'void SetCurrentThreadName(char *)' : cannot convert argument 1 from 'const char [21]' to 'char *'
1>          Conversion from string literal loses const qualifier (see /Zc:strictStrings)
1>WorkingSet.cpp(163): error C2664: 'void SetCurrentThreadName(char *)' : cannot convert argument 1 from 'const char [27]' to 'char *'
1>          Conversion from string literal loses const qualifier (see /Zc:strictStrings)

It was fixed in a previous change.